#! /bin/bash
rm -f TAGS
(
    find $(readlink -f .) \( -name deploy -o -name distributed \) -prune -o \( -regex '.+[.]hp*$' -print \)
    find $(readlink -f .) \( -name deploy -o -name distributed \) -prune -o \( \( -regex '.+[.][cC][cC]?$' -o -regex '.+[.][cC][pP]+$' -o -name '*.S' \) -print \)
) | grep -v -E '(/win32|/CMakeFiles)' | ctags --language-force=c++ -e "$@" -L - -a
chmod -x TAGS 2>/dev/null
