file(APPEND "${UNITTEST_OUTPUT}" "EXIT STATUS: ${UNITTEST_STATUS}\n")

if (${UNITTEST_STATUS})
  message(" FAILURE")
  message("")
  message("====== BEGIN OUTPUT ======")
  if (WIN32)
    execute_process(COMMAND cmd /c type "${UNITTEST_OUTPUT}")
  else()
    execute_process(COMMAND cat "${UNITTEST_OUTPUT}")
  endif(WIN32)
  message("====== END OUTPUT ======")
else()
  message(" OK")
endif()
