file(APPEND "${UNITTEST_OUTPUT}" "EXIT STATUS: ${UNITTEST_STATUS}\n")
get_filename_component(name "${UNITTEST_OUTPUT}" NAME_WE)

if (${UNITTEST_STATUS})
  message("\n====== BEGIN OUTPUT ====== ${name}")
  if (WIN32)
    execute_process(COMMAND cmd /c type "${UNITTEST_OUTPUT}")
  else()
    execute_process(COMMAND cat "${UNITTEST_OUTPUT}")
  endif(WIN32)
  message("====== END OUTPUT ====== ${name}\n")
endif()
